/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : string,
  'status' : string,
  'serviceType' : string,
  'name' : string,
  'description' : string,
  'email' : string,
  'address' : string,
  'preferredTime' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface MechanicApplication {
  'id' : string,
  'status' : string,
  'serviceType' : string,
  'dateOfBirth' : string,
  'name' : string,
  'experience' : string,
  'address' : string,
  'motivation' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllApplications' : ActorMethod<[], Array<MechanicApplication>>,
  'getAllInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getApplicationById' : ActorMethod<[string], MechanicApplication>,
  'getInquiryById' : ActorMethod<[string], ContactInquiry>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'updateApplicationStatus' : ActorMethod<[string, string], undefined>,
  'updateInquiryStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];