/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const MechanicApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'experience' : IDL.Text,
  'address' : IDL.Text,
  'motivation' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'preferredTime' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(MechanicApplication)],
      ['query'],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getApplicationById' : IDL.Func([IDL.Text], [MechanicApplication], ['query']),
  'getInquiryById' : IDL.Func([IDL.Text], [ContactInquiry], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateInquiryStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const MechanicApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'experience' : IDL.Text,
    'address' : IDL.Text,
    'motivation' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'preferredTime' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(MechanicApplication)],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getApplicationById' : IDL.Func(
        [IDL.Text],
        [MechanicApplication],
        ['query'],
      ),
    'getInquiryById' : IDL.Func([IDL.Text], [ContactInquiry], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateInquiryStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };